### ISSUE TITLE
Preferences Over-Written with Upgrade

### ISSUE THREAD

**Issue by Saijin-Naib** [TheJoeFin/Caffeinated#20] opened 2021-01-21 14:41 UTC
Every upgrade/update pushed via the Store resets the preferences of Caffeinated.

So, position in dock, and all settings (regardless of what I had set prior):  
![image](https://user-images.githubusercontent.com/19295950/105365881-bc90e300-5bcc-11eb-868c-cfa2df4715f6.png)

Is there a way to prevent this from happening?

(Absolutely love this, BTW, replaced Insomnia for me!)

**Comment by TheJoeFin** [comment] 2021-01-21 19:23
I have had another user report a similar problem. I tested this on my own device and did not see the settings overwritten, so I'll need to investigate what is going on with AppSettings during an update.

**Comment by Saijin-Naib** [comment] 2021-01-21 20:37
![image](https://user-images.githubusercontent.com/19295950/105409488-85d3c080-5bfe-11eb-8082-2ea86b04ad30.png)
If this helps any

**Comment by TheJoeFin** [comment] 2021-01-29 23:15
Fixed with version 1.3.3. Submitted to store Friday January 29th 2021.

**Comment by Saijin-Naib** [comment] 2021-01-29 23:43
Thank you so much!

What was happening?

**Comment by TheJoeFin** [comment] 2021-01-29 23:50
When updating the Assembly version I didn't call `Settings.Default.Upgrade();` to bring the old settings forward.

**Comment by TheJoeFin** [comment] 2021-02-02 01:24
Not fixed. Just had my settings cleared on update.

**Comment by Saijin-Naib** [comment] 2021-02-02 01:30
Same, just figured it would apply for the next time.

**Comment by Saijin-Naib** [comment] 2021-03-03 13:32
Still occurring as of v1.4

**Comment by TheJoeFin** [comment] 2021-03-03 13:37
Thanks for reporting back, I think the issue is related to the MSIX install. Each update to the app puts all the files in a isolated folder so the WinForms user.config file gets lost and regenerated each time. I will probably have do something different for settings in the future, but I'm not sure exactly what that will be.

**Comment by lalomartins** [comment] 2021-03-05 02:44
Came here to report this, good to know you already figured it out. Not incredible critical anyway, since the configuration is a grand total of 6 options, most of which I don't change 😹 keep up the good work!

Oh, by the way. Every time this happens I also have to drag the tray icon out of the overflow panel (to keep it always visible). I guess some sort of id is also getting lost?

**Comment by TheJoeFin** [comment] 2021-03-15 01:24
Version 1.5 should be the last version which erases settings, after that they should migrate from version to version. Again this is because of the sandboxing done by MSIX.

**Closed by TheJoeFin** 2021-03-15 01:24 UTC
Labels: bug
